<?xml version="1.0"?>
<package format="3">
  <name>servo_trigger</name>
  <version>0.0.1</version>
  <description>Servo motor trigger test via pyserial and ROS2 pose topic</description>
  <maintainer email="user@example.com">user</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
